### ISSUE TITLE
出现未知命令 插件不起作用/ Unknown command plug-in does not work

### ISSUE THREAD

**Issue by nbsdba** [Ryzhehvost/BoosterCreator#10]
我的bot名字是nbsdba
我输入命令 booster nbsdba 570
结果显示 未知错误
![QQ截图20210621171137](https://user-images.githubusercontent.com/20921052/122738468-9757ec00-d2b4-11eb-9fce-d58caac98e1f.png)

**Comment by nbsdba** [comment]
> 
> 
> 我的bot名字是nbsdba
> 我输入命令 booster nbsdba 570
> 结果显示 未知错误
> ![QQ截图20210621171137](https://user-images.githubusercontent.com/20921052/122738468-9757ec00-d2b4-11eb-9fce-d58caac98e1f.png)



> 
> 
> 我的bot名字是nbsdba
> 我输入命令 booster nbsdba 570
> 结果显示 未知命令
> ![QQ截图20210621171137](https://user-images.githubusercontent.com/20921052/122738468-9757ec00-d2b4-11eb-9fce-d58caac98e1f.png)

**Comment by woctezuma** [comment]
Since #7, you need ASF-generic. cf. the README

**Comment by Ryzhehvost** [comment]
As @woctezuma already explained, this plugin only works with ASF-generic.
